### ISSUE TITLE
examples are broken.

### ISSUE THREAD

**Issue by macsimski** [NachtRaveVL/BY8X01-16P-Arduino#2]
in moduleInfo:

-No loop()
-no serial1.begin(9600);
not even a system to end the printmoduleinfo to the host..

in SimpleExample:

-No loop()

i did not dare to check the others.

**Comment by NachtRaveVL** [comment]
Just add a blank loop.

void loop() { }

**Comment by NachtRaveVL** [comment]
Fixed by https://github.com/NachtRaveVL/BY8X01-16P-Arduino/commit/ea137d9839ca3f190d38867f65cb25c090796d43
